[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#212234"
blue = "#7199ee"
cyan = "#38a89d"
green = "#95c561"
magenta = "#a485dd"
red = "#ee6d85"
white = "#a0a8cd"
yellow = "#d7a65f"

[colors.cursor]
cursor = "#a0a8cd"
text = "#11121d"

[colors.normal]
black = "#06080a"
blue = "#7199ee"
cyan = "#38a89d"
green = "#A0E8A2"
magenta = "#a485dd"
red = "#e06c75"
white = "#a0a8cd"
yellow = "#d4b261"

[colors.primary]
background = "#11121d"
foreground = "#a0a8cd"

[colors.selection]
background = "#11121d"
text = "#a0a8cd"

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.bold]
family = "Iosevka"
style = "Bold"

[font.bold_italic]
family = "Iosevka"
style = "Bold Italic"

[font.italic]
family = "Iosevka"
style = "Italic"

[font.normal]
family = "Iosevka"
style = "Normal"

[font.offset]
x = 1
y = 1

# [[schemes.indexed_colors]]
# color = "0xF5D0D0"
# index = 16
# 
# [[schemes.indexed_colors]]
# color = "0x141719"
# index = 17
# 
# [schemes.SAGA.bright]
# black = "0x232628"
# blue = "0xc9ffff"
# cyan = "0x92e5ff"
# green = "0xbeffd2"
# magenta = "0xffc7d5"
# red = "0xffbcb7"
# white = "0xffffff"
# yellow = "0xffffcb"
# 
# [schemes.SAGA.cursor]
# cursor = "0xFFF2FF"
# text = "0x0A0D0F"
# 
# [schemes.SAGA.normal]
# black = "0x191C1E"
# blue = "0xBFFBF9"
# cyan = "0x7ed1f6"
# green = "0xB4F8C8"
# magenta = "0xFFBDCB"
# red = "0xFFB2AD"
# white = "0xFFFCFF"
# yellow = "0xFFFFC1"
# 
# [schemes.SAGA.primary]
# background = "0x0A0D0F"
# foreground = "0xFFF2FF"
# 
# [[schemes.catppuccin.indexed_colors]]
# color = "0xF8BD96"
# index = 16
# 
# [[schemes.catppuccin.indexed_colors]]
# color = "0xF5E0DC"
# index = 17
# 
# [schemes.catppuccin.bright]
# black = "0x988BA2"
# blue = "0x96CDFB"
# cyan = "0x89DCEB"
# green = "0xABE9B3"
# magenta = "0xF5C2E7"
# red = "0xF28FAD"
# white = "0xD9E0EE"
# yellow = "0xFAE3B0"
# 
# [schemes.catppuccin.cursor]
# cursor = "0xF5E0DC"
# text = "0x1E1D2F"
# 
# [schemes.catppuccin.normal]
# black = "0x6E6C7E"
# blue = "0x96CDFB"
# cyan = "0x89DCEB"
# green = "0xABE9B3"
# magenta = "0xF5C2E7"
# red = "0xF28FAD"
# white = "0xD9E0EE"
# yellow = "0xFAE3B0"
# 
# [schemes.catppuccin.primary]
# background = "0x1E1D2F"
# foreground = "0xD9E0EE"
# 
# [schemes.dracula.bright]
# black = "#575b70"
# blue = "#caa9fa"
# cyan = "#9aedfe"
# green = "#5af78e"
# magenta = "#ff92d0"
# red = "#ff6e67"
# white = "#e6e6e6"
# yellow = "#f4f99d"
# 
# [schemes.dracula.normal]
# black = "#000000"
# blue = "#caa9fa"
# cyan = "#8be9fd"
# green = "#50fa7b"
# magenta = "#ff79c6"
# red = "#ff5555"
# white = "#bfbfbf"
# yellow = "#f1fa8c"
# 
# [schemes.dracula.primary]
# background = "#282a36"
# foreground = "#f8f8f2"
# 
# [schemes.gruvbox_dark.bright]
# black = "0x928374"
# blue = "0x83a598"
# cyan = "0x8ec07c"
# green = "0xb8bb26"
# magenta = "0xd3869b"
# red = "0xfb4934"
# white = "0xebdbb2"
# yellow = "0xfabd2f"
# 
# [schemes.gruvbox_dark.normal]
# black = "0x282828"
# blue = "0x458588"
# cyan = "0x689d6a"
# green = "0x98971a"
# magenta = "0xb16286"
# red = "0xcc241d"
# white = "0xa89984"
# yellow = "0xd79921"
# 
# [schemes.gruvbox_dark.primary]
# background = "0x282828"
# foreground = "0xebdbb2"
# 
# [schemes.gruvbox_material_hard_light.bright]
# black = "0x654735"
# blue = "0x45707a"
# cyan = "0x4c7a5d"
# green = "0x6c782e"
# magenta = "0x945e80"
# red = "0xc14a4a"
# white = "0xf2e5bc"
# yellow = "0xb47109"
# 
# [schemes.gruvbox_material_hard_light.normal]
# black = "0x654735"
# blue = "0x45707a"
# cyan = "0x4c7a5d"
# green = "0x6c782e"
# magenta = "0x945e80"
# red = "0xc14a4a"
# white = "0xf2e5bc"
# yellow = "0xb47109"
# 
# [schemes.gruvbox_material_hard_light.primary]
# background = "0xf9f5d7"
# foreground = "0x654735"
# 
# [schemes.gruvbox_material_soft_light.bright]
# black = "0x654735"
# blue = "0x45707a"
# cyan = "0x4c7a5d"
# green = "0x6c782e"
# magenta = "0x945e80"
# red = "0xc14a4a"
# white = "0xe6d5ae"
# yellow = "0xb47109"
# 
# [schemes.gruvbox_material_soft_light.normal]
# black = "0x654735"
# blue = "0x45707a"
# cyan = "0x4c7a5d"
# green = "0x6c782e"
# magenta = "0x945e80"
# red = "0xc14a4a"
# white = "0xe6d5ae"
# yellow = "0xb47109"
# 
# [schemes.gruvbox_material_soft_light.primary]
# background = "0xf2e5bc"
# foreground = "0x654735"
# 
# [schemes.nord.bright]
# black = "#4c566a"
# blue = "#81a1c1"
# cyan = "#8fbcbb"
# green = "#a3be8c"
# magenta = "#b48ead"
# red = "#bf616a"
# white = "#eceff4"
# yellow = "#ebcb8b"
# 
# [schemes.nord.cursor]
# cursor = "#d8dee9"
# text = "#2e3440"
# 
# [schemes.nord.dim]
# black = "#373e4d"
# blue = "#68809a"
# cyan = "#6d96a5"
# green = "#809575"
# magenta = "#8c738c"
# red = "#94545d"
# white = "#aeb3bb"
# yellow = "#b29e75"
# 
# [schemes.nord.normal]
# black = "#3b4252"
# blue = "#81a1c1"
# cyan = "#88c0d0"
# green = "#a3be8c"
# magenta = "#b48ead"
# red = "#bf616a"
# white = "#e5e9f0"
# yellow = "#ebcb8b"
# 
# [schemes.nord.primary]
# background = "#2e3440"
# dim_foreground = "#a5abb6"
# foreground = "#d8dee9"
# 
# [schemes.nord.search.bar]
# background = "#434c5e"
# foreground = "#d8dee9"
# 
# [schemes.nord.search.matches]
# background = "#88c0d0"
# foreground = "CellBackground"
# 
# [schemes.nord.selection]
# background = "#4c566a"
# text = "CellForeground"
# 
# [schemes.nord.vi_mode_cursor]
# cursor = "#d8dee9"
# text = "#2e3440"
# 
# [schemes.solarized_light.bright]
# black = "0x002b36"
# blue = "0x839496"
# cyan = "0x93a1a1"
# green = "0x586e75"
# magenta = "0x6c71c4"
# red = "0xcb4b16"
# white = "0xfdf6e3"
# yellow = "0x657b83"
# 
# [schemes.solarized_light.normal]
# black = "0x073642"
# blue = "0x268bd2"
# cyan = "0x2aa198"
# green = "0x859900"
# magenta = "0xd33682"
# red = "0xdc322f"
# white = "0xeee8d5"
# yellow = "0xb58900"
# 
# [schemes.solarized_light.primary]
# background = "0xfdf6e3"
# foreground = "0x586e75"
# 
# [schemes.tokyodark.bright]
# black = "#212234"
# blue = "#7199ee"
# cyan = "#38a89d"
# green = "#95c561"
# magenta = "#a485dd"
# red = "#ee6d85"
# white = "#a0a8cd"
# yellow = "#d7a65f"
# 
# [schemes.tokyodark.cursor]
# cursor = "#a0a8cd"
# text = "#11121d"
# 
# [schemes.tokyodark.normal]
# black = "#06080a"
# blue = "#7199ee"
# cyan = "#38a89d"
# green = "#A0E8A2"
# magenta = "#a485dd"
# red = "#e06c75"
# white = "#a0a8cd"
# yellow = "#d4b261"
# 
# [schemes.tokyodark.primary]
# background = "#11121d"
# foreground = "#a0a8cd"
# 
# [schemes.tokyodark.selection]
# background = "#11121d"
# text = "#a0a8cd"

[window]
dynamic_title = true
title = "Alacritty"

[window.padding]
x = 10
y = 10
