#!/bin/sh

# Xdbus is generated by the custom script dbus_var_handler.sh
# It is necessary because cron does not see some env variables that are needed for notify-send
if [ -r $HOME/.dotfiles/custom_config/dbus/Xdbus ]; then
  source $HOME/.dotfiles/custom_config/dbus/Xdbus
fi

# Pass 1 as an argument for charging, 0 for discharging
BATTERY_CHARGING=$1
BATTERY_LEVEL=`acpi -b | grep "Battery 0" | grep -P -o '[0-9]+(?=%)'`

# Send notifications
if [ $BATTERY_CHARGING -eq 1 ]; then
    notify-send "Charging" "${BATTERY_LEVEL}% of battery charged." -u low -i "$HOME/.dotfiles/icons/battery-charging-outline.png" -t 5000 -r 9991
elif [ $BATTERY_CHARGING -eq 0 ]; then
    notify-send "Discharging" "${BATTERY_LEVEL}% of battery remaining." -u low -i "$HOME/.dotfiles/icons/battery-arrow-down.png" -t 5000 -r 9991
fi
