#!/bin/sh

wmname LG3D

# autostart my apps
dex -a -s ~/.config/autostart/

# set display(s) resolution
"$HOME"/.screenlayout/xrandr_cmd.sh

# launch polybar
"$HOME"/.config/polybar/launch.sh &

# wallpaper
pgrep -x nitrogen >/dev/null || nitrogen --restore &

# set dbus variables
"$HOME"/.dotfiles/scripts/general/dbus_var_handler.sh

systemctl --user restart sxhkd.service

source "$HOME"/.local/bin/bash-ini-parser/bash-ini-parser

cfg_parser "$HOME"/.screenlayout/monitors_data
cfg_section_displays

if [ "$monitor_count" -eq 1 ]; then
    bspc monitor "$display1" -d 1 2 3 4 5 6 7 8 9 0
elif [ "$monitor_count" -eq 2 ]; then
    bspc monitor "$display1" -d 1 2 3 4 5
    bspc monitor "$display2" -d 6 7 8 9 0
elif [ "$monitor_count" -eq 3 ]; then
    bspc monitor "$display1" -d 1 2 3
    bspc monitor "$display2" -d 4 5 6 7
    bspc monitor "$display3" -d 8 9 0
fi

bspc config top_padding 0

bspc config window_gap 15

bspc config focused_border_color "#7199EE"
bspc config normal_border_color "#565c64"
bspc config border_width 5
bspc config borderless_monocle true

bspc config split_ratio 0.50
bspc config gapless_monocle false

bspc config ignore_ewmh_focus true # to stop apps like discord to allow for follow=off

# The name used is mapped to the WM_CLASS variable.
# You can find it by running `xprop` in the terminal and clicking on the program you
# need info on.
# If that does not work, querying the window with `bspc query` will give the results
# that bspwm needs. Examples:
# - in terminal to get term details: `bspc query -T -n | jq`
# - to get info on all windows in view: `bspc query -T -d | jq`
# They will give all the info you need inclusing the `className`.
bspc rule -a Bitwarden state=floating sticky=on center=true
bspc rule -a Blueman state=floating sticky=on center=true
bspc rule -a Cider desktop='^9' follow=on state=floating sticky=on center=true
bspc rule -a discord desktop='^5' follow=off
bspc rule -a Mailspring desktop='^10' follow=off
# bspc rule -a mpv state=floating sticky=on rectangle=1280x720+320+240
bspc rule -a mpv state=fullscreen
bspc rule -a Oatmeal state=floating center=true rectangle=1050x1050+0+0
bspc rule -a org.gnome.Nautilus state=floating center=true
bspc rule -a Nitrogen state=floating sticky=on center=true
bspc rule -a Nsxiv state=fullscreen
bspc rule -a openrgb state=floating sticky=on center=true
bspc rule -a Pavucontrol state=floating sticky=on center=true
bspc rule -a Pcmanfm state=floating center=true
bspc rule -a Rmpc state=floating sticky=on center=true rectangle=1440x900+0+0
bspc rule -a satty state=floating sticky=on center=true
bspc rule -a teams-for-linux desktop='^9' follow=off
bspc rule -a Thunar state=floating center=true
bspc rule -a XTerm state=floating follow=off
bspc rule -a Yazi state=floating sticky=on center=true rectangle=1440x900+0+0

# custom configs
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
bspc config focus_follows_pointer false

systemctl --user start auto-graphical.service
