#! /bin/sh

wmname LG3D
# export _JAVA_AWT_WM_NONREPARENTING=1

$HOME/.dotfiles/scripts/startup/startup.sh

source $HOME/.local/bin/bash-ini-parser/bash-ini-parser

cfg_parser $HOME/.dotfiles/custom_config/device_config
cfg_section_display

if [ ! -z $secondary ]; then
  bspc monitor $primary -d 1 2 3 4 5
  bspc monitor $secondary -d 6 7 8 9 0
else
  bspc monitor $primary -d 1 2 3 4 5 6 7 8 9 0
fi

bspc config top_padding 0

bspc config window_gap 15

bspc config focused_border_color "#928374"
# bspc config normal_border_color "#11121D"
bspc config border_width 0
bspc config borderless_monocle true

bspc config split_ratio 0.50
bspc config gapless_monocle false

bspc config ignore_ewmh_focus true # to stop apps like discord to allow for follow=off

bspc rule -a Cider desktop='^9' follow=on
bspc rule -a discord desktop='^5' follow=off
bspc rule -a Mailspring desktop='^9' follow=off
bspc rule -a Pavucontrol state=floating sticky=on center=true
bspc rule -a openrgb state=floating sticky=on center=true
bspc rule -a Nitrogen state=floating sticky=on center=true
bspc rule -a Pcmanfm state=floating center=true
bspc rule -a Cider state=floating sticky=on center=true
bspc rule -a mpv state=floating sticky=on
bspc rule -a Blueman state=floating sticky=on center=true

# custom configs
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
bspc config focus_follows_pointer false

$HOME/.dotfiles/scripts/startup/start_after_internet_connect.sh &
