#!/bin/bash

# Xdbus is generated by the custom script dbus_var_handler.sh
# It is necessary because cron does not see some env variables that are needed for notify-send
if [ -r $HOME/.dotfiles/custom_config/dbus/Xdbus ]; then
  source $HOME/.dotfiles/custom_config/dbus/Xdbus
fi

TIME=$(date +%R)
DATE=$(date +'%e %b')

if [[ $(date +%H) == "00" ]]; then
  HEADER="New Day"
  OUTPUT="$DATE\n$TIME"
else
  HEADER="Time"
  OUTPUT="$TIME"
fi

number_word=("zero" "one" "two" "three" "four" "five" "six" "seven" "eight" "nine" "ten" "eleven" "twelve")
TWELVE_HOUR=$(date +%l)
ICON="clock-time-${number_word[$TWELVE_HOUR]}.png"
ICON_PATH="$HOME/.dotfiles/icons/${ICON}"

dunstify -i $ICON_PATH -u low "$HEADER" "$OUTPUT" -t 2000
