[mgr]
ratio = [ 1, 4, 5 ]

[preview]
image_delay = 0
image_filter = "nearest"
image_quality = 50

[opener]
edit = [
  { run = 'nvim "$@"', desc = "Edit (nvim)", block = true, for = "unix" },
]
open = [
  { run = '$HOME/.dotfiles/scripts/yazi/hide_open_unhide xdg-open "$@"', block = true, desc = "Open (default)", for = "unix" },
]
reveal = [
  { run = 'xdg-open "$(dirname "$1")"', desc = "Reveal", for = "linux" },
  { run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
  { run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
]
play = [
  { run = '$HOME/.dotfiles/scripts/yazi/hide_open_unhide mpv "$@"', block = true, desc = "Play", for = "unix" },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]
pdf = [
  { run = '$HOME/.dotfiles/scripts/yazi/hide_open_unhide libreoffice "$@"', block = true, desc = "Open (libreoffice)", for = "unix" },
  { run = '$HOME/.dotfiles/scripts/yazi/hide_open_unhide xournalpp "$@"', block = true, desc = "Open (xournalpp)", for = "unix" },
  { run = '$HOME/.dotfiles/scripts/yazi/hide_open_unhide zathura "$@"', block = true, desc = "Open (zathura)", for = "unix" },
]
office = [
  { run = '$HOME/.dotfiles/scripts/yazi/hide_open_unhide libreoffice "$@"', block = true, desc = "Open (libreoffice)", for = "unix" },
]

[open]
rules = [
  # Folder
  { name = "*/", use = [
    "reveal",
  ] },
  # Text
  { mime = "text/*", use = [
    "edit",
    "reveal",
  ] },
  # PDF
  { mime = "application/{pdf}", use = [
    "pdf",
  ] },
  # Office Docs
  # Not sure why I can't use the mime type. Oh well...
  { name = "*.docx", use = [ "office" ] },
  { name = "*.doc", use = [ "office" ] },
  { name = "*.xlsx", use = [ "office" ] },
  { name = "*.xls", use = [ "office" ] },
  { name = "*.pptx", use = [ "office" ] },
  { name = "*.ppt", use = [ "office" ] },
  # Image
  { mime = "image/*", use = [
    "open",
    "reveal",
  ] },
  # Media
  { mime = "{audio,video}/*", use = [
    "play",
    "reveal",
  ] },
  # Archive
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [
    "extract",
    "reveal",
  ] },
  # JSON
  { mime = "application/{json,ndjson}", use = [
    "edit",
    "reveal",
  ] },
  { mime = "*/javascript", use = [
    "edit",
    "reveal",
  ] },
  # Empty file
  { mime = "inode/empty", use = [
    "edit",
    "reveal",
  ] },
  # Fallback
  { name = "*", use = [
    "open",
    "reveal",
  ] },
]
